#!/usr/bin/env bash
# Type-check the app's Java on the HOST, without an Android SDK.
#
# ── THE HOLE THIS FILLS ───────────────────────────────────────────────────────
#
# `tools/check-jni.sh` checks the RUST side of the JNI seam. The JAVA side — ten
# classes, 6,500 lines, including `NwdBridge`, which is where the tuner and the
# sleep/wake work actually live — was checked by nothing at all. It is compiled
# only by Gradle, on the owner's machine, at the end of a build, and a mistake in
# it is found there or on the unit.
#
# That has cost real time. #133's kill-signal receiver was written with a
# `static final` field referenced from an array initializer ABOVE its own
# declaration — an illegal forward reference, a hard compile error, and invisible
# to every check this container had.
#
# ── HOW ───────────────────────────────────────────────────────────────────────
#
# A real Android framework jar (Robolectric's `android-all`, which is the AOSP
# framework with method bodies) is enough to type-check against. It is ~137 MB;
# this script fetches it to a temp directory and DELETES IT AGAIN unless
# `ANDROID_ALL_JAR` names one to keep.
#
# ── THE VENDOR INTERFACES COME FROM OUR OWN .aidl, NOT FROM THE APK ──────────
#
# `RadioFeature` and `RadioCallback` are `.aidl` in this tree; Gradle runs the
# AIDL compiler over them and javac cannot. So this generates a Java interface
# from each — signatures only, no bodies — into a temp directory.
#
# GENERATED FROM THE .aidl AND NOT FROM THE VENDOR'S APK, deliberately. The
# licensing note those files carry is explicit: "do not redistribute decompiled
# code, modified APKs, or firmware". Deriving the stub from the hand-written
# declaration keeps this check on the right side of that, and is also the more
# correct thing to check against — the AIDL is what the real build compiles.
#
# The two data parcelables are already `.java` in the tree and are used as-is.
#
# ── WHAT IS SKIPPED, AND WHY ──────────────────────────────────────────────────
#
# `CarnyxNav` needs eleven OsmAnd AIDL parcelables whose generated forms are more
# than signatures — they carry `Parcelable` plumbing this generator does not
# emit. Named and printed rather than silently dropped, on the same rule
# `check-jni.sh` states over its own skip list.
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$PWD"
OUT="$(mktemp -d)"
JAR="${ANDROID_ALL_JAR:-}"
FETCHED=""

cleanup() {
    rm -rf "$OUT"
    [ -n "$FETCHED" ] && rm -f "$FETCHED" || true
}
trap cleanup EXIT

if [ -z "$JAR" ]; then
    JAR="$OUT/android-all.jar"
    FETCHED="$JAR"
    echo "fetching the framework jar (~137 MB; set ANDROID_ALL_JAR to keep one)"
    curl -sSL -o "$JAR" \
        "https://repo1.maven.org/maven2/org/robolectric/android-all/14-robolectric-10818077/android-all-14-robolectric-10818077.jar"
fi
[ -s "$JAR" ] || { echo "no framework jar at $JAR" >&2; exit 1; }

# ── Generate an interface per .aidl ──────────────────────────────────────────
mkdir -p "$OUT/stubs"
python3 - "$ROOT" "$OUT/stubs" <<'PY'
import os, re, sys
root, out = sys.argv[1], sys.argv[2]
aidl_dir = os.path.join(root, "java", "com", "nwd", "radio", "service")
made = []
for name in sorted(os.listdir(aidl_dir)):
    if not name.endswith(".aidl"):
        continue
    text = open(os.path.join(aidl_dir, name)).read()
    m = re.search(r"(?m)^\s*interface\s+(\w+)\s*\{", text)
    if not m:
        continue                      # a `parcelable X;` declaration, not an interface
    iface = m.group(1)
    body = text[m.end():]
    body = body[: body.rindex("}")]
    methods = []
    for line in body.split("\n"):
        line = line.split("//")[0].strip()
        if not line.endswith(";"):
            continue
        # AIDL directions have no Java equivalent and are dropped.
        line = re.sub(r"\b(in|out|inout)\s+", "", line)
        methods.append("    public " + line)
    pkg = "com.nwd.radio.service"
    src = ["package %s;" % pkg,
           "import com.nwd.radio.service.data.Frequency;",
           "import com.nwd.radio.service.data.RadioPoint;",
           "/** Generated by tools/check-java.sh from %s. Signatures only. */" % name,
           "public interface %s extends android.os.IInterface {" % iface]
    src += methods
    src += ["    abstract class Stub extends android.os.Binder implements %s {" % iface,
            "        public static %s asInterface(android.os.IBinder b) { return null; }" % iface,
            "        public android.os.IBinder asBinder() { return this; }",
            "    }",
            "}"]
    d = os.path.join(out, *pkg.split("."))
    os.makedirs(d, exist_ok=True)
    open(os.path.join(d, iface + ".java"), "w").write("\n".join(src) + "\n")
    made.append("%s (%d methods)" % (iface, len(methods)))
print("generated from .aidl: " + ", ".join(made))
PY

# ── Compile ─────────────────────────────────────────────────────────────────
SKIP="CarnyxNav.java"
SOURCES=()
for f in java/com/ninthfreak/carnyx/*.java android/app/src/main/java/com/ninthfreak/carnyx/*.java; do
    case "$(basename "$f")" in
        $SKIP) continue ;;
    esac
    SOURCES+=("$f")
done
echo "checking: $(printf '%s\n' "${SOURCES[@]}" | xargs -n1 basename | tr '\n' ' ')"
echo "skipping: $SKIP (needs the OsmAnd AIDL parcelables)"

LOG="$OUT/javac.log"
set +e
# `-Xmaxwarns` IS NOT OPTIONAL HERE. javac stops printing after 100 warnings, and
# the framework jar's own `UnsupportedAppUsage` annotations produce 635 of them —
# so at the default cap NOT ONE of our own diagnostics is ever printed, and this
# script reported a clean tree while the deprecations below sat unmentioned.
javac -Xlint:all -Xmaxwarns 2000 -classpath "$JAR" -sourcepath "java:$OUT/stubs" \
    -d "$OUT/classes" "${SOURCES[@]}" 2> "$LOG"
rc=$?
set -e

# ERRORS FAIL; WARNINGS ARE REPORTED AND DO NOT. The jar's own
# `UnsupportedAppUsage` annotations produce a hundred warnings that name the JAR
# rather than our files, so only diagnostics naming a source file count at all —
# and of those, the deprecations are pre-existing and true (a GNSS callback, two
# `URL` constructors, `Configuration.locale`, `BaseBundle.get`). A check that is
# red on the day it lands is a check nobody runs, so those are printed and
# counted, and the exit code is about errors.
OURS='^(java|android)/.*\.java:[0-9]+:'
if grep -qE "$OURS error" "$LOG"; then
    grep -E "$OURS error" -A 3 "$LOG" >&2
    echo >&2
    echo "Java does NOT compile." >&2
    exit 1
fi
if [ "$rc" -ne 0 ]; then
    cat "$LOG" >&2
    echo "javac failed for a reason that names no source file." >&2
    exit 1
fi

warns="$(grep -cE "$OURS warning" "$LOG" || true)"
if [ "$warns" -gt 0 ]; then
    echo
    echo "$warns warning(s) in our sources, none of them fatal:"
    grep -E "$OURS warning" "$LOG" | sed 's/^/  /'
fi

echo
echo "Java compiles: $(find "$OUT/classes" -name '*.class' | wc -l | tr -d ' ') classes, no error in our sources."
